[config]
default_to_workspace = false
additional_profiles = ["debug"]

[env]
RUST_BACKTRACE = 0

[tasks.choose_profile.env]
MODE = "release"
ADDITIONAL = "--release"

    [tasks.choose_profile.env.debug]
    MODE = "debug"
    ADDITIONAL = "--profile=dev"


[tasks.fmt-check]
toolchain = "nightly"
command = "cargo"
args = ["fmt", "--check"]

[tasks.clippy]
toolchain = "stable"
command = "cargo"
args = ["clippy", "--all-targets", "--", "-D", "warnings"]

[tasks.lint]
dependencies = ["fmt-check", "clippy"]


[tasks.lint-test]
toolchain = "stable"
command = "cargo"
args = ["test"]
dependencies = ["lint"]
